.TH mascara 1

.SH NAME
mascara - tokenize a text file

.SH SYNOPSIS
.B mascara
.RB [-l\ <lang>]\ [-f\ <format>]\ [-e\ <eos>]\ [--]\ [<file>]

.SH DESCRIPTION
.SS Overview
Mascara is a natural language tokenizer. It segments a text into tokens, and,
optionally, sentences.

.SS Options

.TP
.B \-l, \-\-lang=<string> [en]
Language of the text to tokenize. Use the
.B \-L
option to obtain a list of the supported languages. If a language for which
there is no specific support is given, a generic tokenizer will be used.

.TP
.B \-f, \-\-format=<string> [%s\\\\n]
Token format string. The following substitutions are performed:

   %s    token string
   %t    token type
   %l    token length, in bytes
   %o    token offset, in bytes
   \\n    newline
   \\t    tabulation
   \\\\    backslash

Unknown escape sequences are emitted as is.

.TP
.B \-e, \-\-eos=<string> [\\\\n]
String to display at the end of a sentence. Passing the empty string disables
sentence segmentation. Supports the same escape sequences as the
.B \-f
option.

.TP
.B \-L, \-\-list
Display a list of the supported languages. Language names are abbreviated to an
ISO 639-1 two-letters code.

.TP
.B \-h, \-\-help
Display a short help message.
.TP
.B \-\-version
Display the library version.

.SS Note
The variable
.B MR_HOME
can be defined to change the directory where model files are looked up. Per
default, model files are searched in $PREFIX/share/mascara, the value of $PREFIX
being defined before installation and defaulting to /usr/local.

.SH COPYRIGHT
Copyright (c) 2016 Michaël Meyer
